### 2021_11_08_2

### CNN(Convolution Neural Network) - 합성곱 신경망

In [2]:
import os, warnings

warnings.filterwarnings(action='ignore')

In [3]:
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers

In [4]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation = "relu", 
                      input_shape = (28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation = "relu"))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation = "relu"))

model.add(layers.Flatten()) # 1차원으로 변환
model.add(layers.Dense(64, activation = "relu"))
model.add(layers.Dense(10, activation = "softmax"))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten (Flatten)            (None, 576)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                3

### 데이터 준비

In [5]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [6]:
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype("float32") / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype("float32") / 255

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [7]:
print(train_labels[0 : 10])
print("train_labels shape :", train_labels.shape)
print("test_labels shape :", test_labels.shape)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
train_labels shape : (60000, 10)
test_labels shape : (10000, 10)


In [10]:
%%time

model.compile(optimizer = "sgd", 
              loss = "categorical_crossentropy", 
              metrics = ["accuracy"])
model.fit(train_images, train_labels, epochs = 25, batch_size = 64, 
          validation_data = (test_images, test_labels))

Epoch 1/25
938/938 [==============================] - 8s 8ms/step - loss: 0.0458 - accuracy: 0.9859 - val_loss: 0.0754 - val_accuracy: 0.9736
Epoch 2/25
938/938 [==============================] - 7s 8ms/step - loss: 0.0434 - accuracy: 0.9862 - val_loss: 0.0575 - val_accuracy: 0.9829
Epoch 3/25
938/938 [==============================] - 7s 8ms/step - loss: 0.0415 - accuracy: 0.9868 - val_loss: 0.0477 - val_accuracy: 0.9838
Epoch 4/25
938/938 [==============================] - 7s 8ms/step - loss: 0.0385 - accuracy: 0.9882 - val_loss: 0.0400 - val_accuracy: 0.9870
Epoch 5/25
938/938 [==============================] - 7s 8ms/step - loss: 0.0370 - accuracy: 0.9886 - val_loss: 0.0376 - val_accuracy: 0.9875
Epoch 6/25
938/938 [==============================] - 7s 8ms/step - loss: 0.0355 - accuracy: 0.9886 - val_loss: 0.0453 - val_accuracy: 0.9853
Epoch 7/25
938/938 [==============================] - 7s 7ms/step - loss: 0.0336 - accuracy: 0.9900 - val_loss: 0.0437 - val_accuracy: 0.9852
Epoch 

In [ ]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)