### 2021_10_21_3

### 01. 데이터 준비

In [1]:
import pandas as pd
data = { "feature1":[2,3,8,4],
         "feature2":[22,32,82,42],
         "target": ["b","c", "a", "d"]
       }
df = pd.DataFrame(data)
df

feature1  feature2 target
0         2        22      b
1         3        32      c
2         8        82      a
3         4        42      d

### Label Encoding

In [2]:
from sklearn import preprocessing

In [3]:
label_encoder = preprocessing.LabelEncoder()
df['lbl_en'] = label_encoder.fit_transform(df['target'])
df

feature1  feature2 target  lbl_en
0         2        22      b       1
1         3        32      c       2
2         8        82      a       0
3         4        42      d       3

In [4]:
train_y = df['lbl_en'].values.reshape(len(df), 1)

onehot_encoder = preprocessing.OneHotEncoder(sparse=False)
train_y_onehot = onehot_encoder.fit_transform(train_y)
print(train_y_onehot)
print(train_y_onehot.shape)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [5]:
import pandas as pd
import os

In [6]:
demo_df = pd.DataFrame({"범주형_feature":['양말', '여우', '양말', '상자']})
display(demo_df)

범주형_feature
0          양말
1          여우
2          양말
3          상자

In [7]:
onehot = pd.get_dummies(demo_df)
onehot

범주형_feature_상자  범주형_feature_양말  범주형_feature_여우
0               0               1               0
1               0               0               1
2               0               1               0
3               1               0               0

In [8]:
df = pd.concat([demo_df, onehot], axis=1)
df

범주형_feature  범주형_feature_상자  범주형_feature_양말  범주형_feature_여우
0          양말               0               1               0
1          여우               0               0               1
2          양말               0               1               0
3          상자               1               0               0