### 2021_10_29_3

## 추천 시스템(Recommendation System)
### 협업 필터링(collaborative filtering)

| |피자|치킨|김밥|탕수육|
|-|--|--|--|--|
|고객1|좋다|좋다|X|좋다|
|고객2|X|X|좋다|X|
|고객3|좋다|좋다|X|?|


In [10]:
import numpy as np
import pandas as pd

### 사용자 기반 협업 필터링

In [3]:
user1 = np.array([2, 2, 1, 2])
user2 = np.array([1, 1, 2, 1])
user3 = np.array([2, 2, 1, 0])

rMatrix = np.vstack((user1, user2, user3))
print(rMatrix.shape)
rMatrix

(3, 4)


array([[2, 2, 1, 2],
       [1, 1, 2, 1],
       [2, 2, 1, 0]])

### 사이킷 런의 cosine_similarity함수를 이용한 코사인 유사도

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

cosineSim = cosine_similarity(rMatrix)
print(cosineSim.shape)
cosineSim

(3, 3)


array([[1.        , 0.83862787, 0.83205029],
       [0.83862787, 1.        , 0.75592895],
       [0.83205029, 0.75592895, 1.        ]])

||||
|-|-|-|
| user1 user1 | user1 user2 | user1 user3 |
| user2 user1 | user2 user2 | user2 user3 |
| user3 user1 | user3 user2 | user3 user3 |


### 아이템 기반 협업 필터링

||user1|user2|user3|
|-|-|-|-|
|피자| | | |
|치킨||||
|김밥||||
|탕수육||||

In [6]:
rMatrix_t = np.transpose(rMatrix)
print(rMatrix_t.shape)
rMatrix_t

(4, 3)


array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [2, 1, 0]])

In [7]:
cosineSim_t = cosine_similarity(rMatrix_t)
cosineSim_t

array([[1.        , 1.        , 0.81649658, 0.74535599],
       [1.        , 1.        , 0.81649658, 0.74535599],
       [0.81649658, 0.81649658, 1.        , 0.73029674],
       [0.74535599, 0.74535599, 0.73029674, 1.        ]])

|||||
|-|-|-|-|
|피자 피자|피자 치킨|피자 김밥|피자 탕수육|
|치킨 피자|치킨 치킨|치킨 김밥|치킨 탕수육|
|김밥 피자|김밥 치킨|김밥 김밥|김밥 탕수육|
|탕수육 피자|탕수육 치킨|탕수육 김밥|피자 탕수육|

* 탕수육과 피자(or 치킨)은 비슷한 선호도(0.7453559)를 갖는다.