In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../CSV/result.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3945 entries, 0 to 3944
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   지점번호           3945 non-null   int64  
 1   지점명            3945 non-null   object 
 2   일시             3945 non-null   object 
 3   평균기온(℃)        3945 non-null   float64
 4   최고기온(℃)        3945 non-null   float64
 5   최고기온시각         3945 non-null   object 
 6   최저기온(℃)        3945 non-null   float64
 7   최저기온시각         3945 non-null   object 
 8   일교차            3945 non-null   float64
 9   강수량(mm)        3945 non-null   float64
 10  1시간최다강수량(mm)   3945 non-null   float64
 11  1시간최다강수량시각     3945 non-null   object 
 12  평균풍속(m/s)      3945 non-null   float64
 13  최대풍속(m/s)      3945 non-null   float64
 14  최대풍속풍향(deg)    3945 non-null   float64
 15  최대풍속시각         3945 non-null   object 
 16  최대순간풍속(m/s)    3945 non-null   float64
 17  최대순간풍속풍향(deg)  3945 non-null   float64
 18  최대순간풍속시각

In [5]:
data.columns

Index(['지점번호', '지점명', '일시', '평균기온(℃)', '최고기온(℃)', '최고기온시각', '최저기온(℃)',
       '최저기온시각', '일교차', '강수량(mm)', '1시간최다강수량(mm)', '1시간최다강수량시각', '평균풍속(m/s)',
       '최대풍속(m/s)', '최대풍속풍향(deg)', '최대풍속시각', '최대순간풍속(m/s)', '최대순간풍속풍향(deg)',
       '최대순간풍속시각', '평균습도(%rh)', '최저습도(%rh)', '평균', '평년', '서울', '부산', '대구',
       '광주', '대전'],
      dtype='object')

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [14]:
X = data[["평균기온(℃)", "최고기온(℃)", "최저기온(℃)", "강수량(mm)", '일교차', '평균풍속(m/s)', '평균습도(%rh)', '최저습도(%rh)']]
y = data["광주"]

In [20]:
for i in range(1, 6, 1) :
    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = LinearRegression().fit(X_train, y_train)
    pred = model.predict(X_test)
    
    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)
    
    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5
    
    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()

학습용 : 9, 테스트용 : 1
학습용 : 0.1358378157226362, 테스트용 : 0.12605166819715907
MAE : 7986.018804981731
MSE : 100953685.51549608
RMSE : 10047.571125177272

학습용 : 8, 테스트용 : 2
학습용 : 0.13769125883792532, 테스트용 : 0.12257184750152628
MAE : 7901.659941852359
MSE : 98635357.0430948
RMSE : 9931.533468860425

학습용 : 7, 테스트용 : 3
학습용 : 0.12971519040431545, 테스트용 : 0.14070180504840968
MAE : 7800.334701080472
MSE : 97698040.67080003
RMSE : 9884.231921135806

학습용 : 6, 테스트용 : 4
학습용 : 0.12458801559523924, 테스트용 : 0.14403031867562677
MAE : 7737.368084888357
MSE : 95273701.96635866
RMSE : 9760.824860961222

학습용 : 5, 테스트용 : 5
학습용 : 0.1254277444923496, 테스트용 : 0.1381534270191237
MAE : 7698.837347391483
MSE : 93642143.15999267
RMSE : 9676.887059379822



In [7]:
from sklearn.tree import DecisionTreeRegressor

In [42]:
for i in range(1, 6, 1) :
    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = DecisionTreeRegressor(max_depth = 20, random_state = 0).fit(X_train, y_train)
    pred = model.predict(X_test)

    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5

    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()

학습용 : 9, 테스트용 : 1
학습용 : 0.9796690153914186, 테스트용 : -0.6167501209304227
MAE : 10326.086899388738
MSE : 186758046.5870964
RMSE : 13665.944774771204

학습용 : 8, 테스트용 : 2
학습용 : 0.9772085165518597, 테스트용 : -0.5418308018253171
MAE : 9997.605244002581
MSE : 173323629.06870127
RMSE : 13165.24322102335

학습용 : 7, 테스트용 : 3
학습용 : 0.9731637953567835, 테스트용 : -0.5639789188906332
MAE : 10179.806905165979
MSE : 177816824.15224788
RMSE : 13334.79749198494

학습용 : 6, 테스트용 : 4
학습용 : 0.9875920524610281, 테스트용 : -0.5384448608048666
MAE : 9937.281618008805
MSE : 171236599.09684867
RMSE : 13085.74029609516

학습용 : 5, 테스트용 : 5
학습용 : 0.9890199652783628, 테스트용 : -0.6184627412546508
MAE : 10065.546813195066
MSE : 175850696.01366866
RMSE : 13260.870861812533



In [8]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
for i in range(1, 6, 1) :
    X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                       test_size = (i / 10),
                                                       random_state = 42)
    model = RandomForestRegressor().fit(X_train, y_train)
    pred = model.predict(X_test)

    train_score = model.score(X_train, y_train)
    test_score = model.score(X_test, y_test)

    mae_val = np.abs(y_test - pred).sum() / len(pred)
    mse_val = ((y_test - pred) ** 2).sum() / len(pred)
    rmse_val = mse_val ** 0.5

    print(f"학습용 : {10 - i}, 테스트용 : {i}")
    print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
    print("MAE : {}".format(mae_val))
    print("MSE : {}".format(mse_val))
    print("RMSE : {}".format(rmse_val))
    print()

dict_dat = {"실제값" : y_test, "예측값" : pred, "오차" : y_test - pred}
dat = pd.DataFrame(dict_dat)
dat.head(10)

학습용 : 9, 테스트용 : 1
학습용 : 0.8824041494789099, 테스트용 : 0.14199844066350653
MAE : 7767.868354430379
MSE : 99111602.41518988
RMSE : 9955.481023797387

학습용 : 8, 테스트용 : 2
학습용 : 0.882161176614729, 테스트용 : 0.13158459287971946
MAE : 7817.575411913815
MSE : 97622196.756654
RMSE : 9880.394564826549

학습용 : 7, 테스트용 : 3
학습용 : 0.8812195884341212, 테스트용 : 0.14144181562696945
MAE : 7721.574324324324
MSE : 97613905.05405405
RMSE : 9879.97495209649

학습용 : 6, 테스트용 : 4
학습용 : 0.8810858063722167, 테스트용 : 0.13139144851952667
MAE : 7701.707224334601
MSE : 96680471.35868187
RMSE : 9832.622811777226

학습용 : 5, 테스트용 : 5
학습용 : 0.8785375262214702, 테스트용 : 0.11767224646530838
MAE : 7674.381652306133
MSE : 95867483.1469843
RMSE : 9791.194163480995



실제값      예측값       오차
3713  44300.0  21813.0  22487.0
2251  26000.0  32641.0  -6641.0
1872  20000.0  31295.0 -11295.0
729   23000.0  25438.0  -2438.0
605   32000.0  36281.0  -4281.0
402   29000.0  26134.0   2866.0
2775  40000.0  38318.0   1682.0
3509  70300.0  39549.0  30751.0
2807  36000.0  47381.0 -11381.0
3836  49300.0  35427.0  13873.0

In [9]:
from sklearn.cluster import KMeans

In [30]:
kmeans = KMeans(n_clusters = 2)
kmeans.fit(X_train)
y_pred = kmeans.predict(X_test)

train_score = kmeans.score(X_train, y_train)
test_score = kmeans.score(X_test, y_test)
print(train_score, test_score)

-1025106.3689783949 -933833.460333271


In [10]:
from sklearn.linear_model import Ridge

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

ridge = Ridge().fit(X_train, y_train)

train_score = ridge.score(X_train, y_train)
test_score = ridge.score(X_test, y_test)
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))

NameError: name 'X' is not defined

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

ridge = Ridge(alpha = 0.1).fit(X_train, y_train)

train_score = ridge.score(X_train, y_train)
test_score = ridge.score(X_test, y_test)
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))

학습용 : 0.13589412573930737, 테스트용 : 0.13110726551107776


In [16]:
from sklearn.linear_model import Lasso

lasso = Lasso().fit(X_train, y_train)

train_score = lasso.score(X_train, y_train)
test_score = lasso.score(X_test, y_test)
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
print("사용한 특성의 개수 : {}".format(np.sum(lasso.coef_ != 0)))

학습용 : 0.1358939627064093, 테스트용 : 0.13109720266794211
사용한 특성의 개수 : 8


/Users/seungwoomun/opt/anaconda3/envs/likelion/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:645: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.616e+10, tolerance: 3.066e+07
  model = cd_fast.enet_coordinate_descent(


In [17]:
lasso = Lasso(alpha = 0.00001, max_iter = 10000000).fit(X_train, y_train)

train_score = lasso.score(X_train, y_train)
test_score = lasso.score(X_test, y_test)
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))
print("사용한 특성의 개수 : {}".format(np.sum(lasso.coef_ != 0)))

학습용 : 0.1358941257527324, 테스트용 : 0.13112005160352103
사용한 특성의 개수 : 8


In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
logreg = LogisticRegression().fit(X_train, y_train)

train_score = logreg.score(X_train, y_train)
test_score = logreg.score(X_test, y_test)
print("학습용 : {}, 테스트용 : {}".format(train_score, test_score))

학습용 : 0.09939148073022312, 테스트용 : 0.09523809523809523


/Users/seungwoomun/opt/anaconda3/envs/likelion/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
X = data[["평균기온(℃)", '최고기온(℃)', '최저기온(℃)', '강수량(mm)', '일교차', '강수량(mm)', '평균풍속(m/s)',
       '최대풍속(m/s)', '평균습도(%rh)', '최저습도(%rh)']]
y = data["평균"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = (4 / 10), random_state = 42)

# LinearRegression
lr = LinearRegression().fit(X_train, y_train)
lr_pred = lr.predict(X_test)

train_score = lr.score(X_train, y_train)
test_score = lr.score(X_test, y_test)

print("LinearRegression")
print("학습용 정확도 : {}, 테스트용 정확도 : {}".format(train_score, test_score))
print()

# DecisionTreeRegressor
tree = DecisionTreeRegressor().fit(X_train, y_train)
tree_pred = tree.predict(X_test)

train_score = tree.score(X_train, y_train)
test_score = tree.score(X_test, y_test)

print("DecisionTreeRegressor")
print("학습용 정확도 : {}, 테스트용 정확도 : {}".format(train_score, test_score))
print()

# RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100).fit(X_train, y_train)
rf_pred = rf.predict(X_test)

train_score = rf.score(X_train, y_train)
test_score = rf.score(X_test, y_test)

print("RandomForestRegressor")
print("학습용 정확도 : {}, 테스트용 정확도 : {}".format(train_score, test_score))
print()

# Ridge
ridge = Ridge(alpha = 0.1).fit(X_train, y_train)
ridge_pred = ridge.predict(X_test)

train_score = ridge.score(X_train, y_train)
test_score = ridge.score(X_test, y_test)

print("Ridge")
print("학습용 정확도 : {}, 테스트용 정확도 : {}".format(train_score, test_score))
print()

# Lasso
lasso = Lasso().fit(X_train, y_train)
lasso_pred = lasso.predict(X_test)

train_score = lasso.score(X_train, y_train)
test_score = lasso.score(X_test, y_test)

print("Lasso")
print("학습용 정확도 : {}, 테스트용 정확도 : {}".format(train_score, test_score))

LinearRegression
학습용 정확도 : 0.1393813353466936, 테스트용 정확도 : 0.1584190703818502

DecisionTreeRegressor
학습용 정확도 : 1.0, 테스트용 정확도 : -0.5502246003715252

RandomForestRegressor
학습용 정확도 : 0.8811338468470196, 테스트용 정확도 : 0.16022258766236408

Ridge
학습용 정확도 : 0.13938133298459965, 테스트용 정확도 : 0.1584204578855346

Lasso
학습용 정확도 : 0.13937825724806652, 테스트용 정확도 : 0.15846678711731566


/Users/seungwoomun/opt/anaconda3/envs/likelion/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:645: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.954e+10, tolerance: 1.928e+07
  model = cd_fast.enet_coordinate_descent(


In [23]:
from sklearn.model_selection import cross_val_score, KFold

In [24]:
lr_scores = cross_val_score(lr, X_train, y_train)
print("LinearRegression scores : {}".format(lr_scores))
tree_scores = cross_val_score(tree, X_train, y_train)
print("DecisionTree scores : {}".format(tree_scores))
rf_scores = cross_val_score(rf, X_train, y_train)
print("RandomForest scores : {}".format(rf_scores))

LinearRegression scores : [0.11841996 0.10700283 0.10010639 0.13385765 0.17001103]
DecisionTree scores : [-0.79421959 -0.7354981  -0.64225204 -0.5006558  -0.5727883 ]
RandomForest scores : [0.1117692  0.10347918 0.10675031 0.1427222  0.19530091]


In [25]:
kfold = KFold(n_splits = 5, shuffle = True, random_state = 0)

print("LinearRegression")
lr_train_scores = cross_val_score(lr, X_train, y_train, cv = kfold)
print("train 교차 검증 점수 :\n{}".format(lr_train_scores))
lr_test_scores = cross_val_score(lr, X_test, y_test, cv = kfold)
print("test 교차 검증 점수 :\n{}".format(lr_test_scores))
print()

print("DecisionTree")
tree_train_scores = cross_val_score(tree, X_train, y_train, cv = kfold)
print("train 교차 검증 점수 :\n{}".format(tree_train_scores))
tree_test_scores = cross_val_score(tree, X_test, y_test, cv = kfold)
print("test 교차 검증 점수 :\n{}".format(tree_test_scores))
print()

print("RandomForest")
rf_train_scores = cross_val_score(rf, X_train, y_train, cv = kfold)
print("train 교차 검증 점수 :\n{}".format(rf_train_scores))
rf_test_scores = cross_val_score(rf, X_test, y_test, cv = kfold)
print("test 교차 검증 점수 :\n{}".format(rf_test_scores))

LinearRegression
train 교차 검증 점수 :
[0.11368321 0.13591501 0.09097696 0.18429343 0.1261977 ]
test 교차 검증 점수 :
[-5.52864991e+20  1.88481673e-01  1.40421593e-01  1.76460306e-01
  1.03291185e-01]

DecisionTree
train 교차 검증 점수 :
[-0.56728235 -0.85927947 -0.53967529 -0.71583105 -0.40768388]
test 교차 검증 점수 :
[-0.90425665 -0.42829368 -0.38773471 -0.68552491 -0.53093237]

RandomForest
train 교차 검증 점수 :
[0.1471839  0.09309386 0.16866402 0.18840964 0.16205428]
test 교차 검증 점수 :
[0.21695047 0.17529004 0.15298503 0.13753823 0.07838464]
